version: "3"

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=price_db
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev price_db" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: null
